
package org.imie.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Apr 03 05:20:54 CEST 2013
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "executeService", namespace = "http://imie.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeService", namespace = "http://imie.org/")

public class ExecuteService {


}

