
package org.imie.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Apr 03 05:20:54 CEST 2013
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "executeServiceResponse", namespace = "http://imie.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeServiceResponse", namespace = "http://imie.org/")

public class ExecuteServiceResponse {

    @XmlElement(name = "return")
    private java.util.List<java.lang.String> _return;

    public java.util.List<java.lang.String> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<java.lang.String> new_return)  {
        this._return = new_return;
    }

}

