package org.imie;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-04-03T06:02:50.945+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://imie.org/", name = "BasicService")
@XmlSeeAlso({ObjectFactory.class})
public interface BasicService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "executeService", targetNamespace = "http://imie.org/", className = "org.imie.ExecuteService")
    @WebMethod
    @ResponseWrapper(localName = "executeServiceResponse", targetNamespace = "http://imie.org/", className = "org.imie.ExecuteServiceResponse")
    public java.util.List<java.lang.String> executeService();
}
